"""Add likes_count to comments

Revision ID: 312518ae6e98
Revises: 82c1b5cd4370
Create Date: 2025-12-24 14:04:10.536205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312518ae6e98'
down_revision = '82c1b5cd4370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_user_anime_review'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_user_anime_review'), ['user_id', 'anime_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
